### ISSUE TITLE
Add documentation for the "CONTENT MANAGEMENT" topic

### ISSUE THREAD

**Issue by alecghica** [plone/training.plone.org#13]
The [CONTENT MANAGEMENT](https://training.plone.org) section provide no info for this topic, it just redirects you to the landing page of the [training.plone.org](https://training.plone.org). I see there is already documentation for this topic under:

- http://docs.plone.org/working-with-content/index.html
- http://docs.plone.org/4/en/working-with-content/index.html

... which can be added for the "CONTENT MANAGEMENT" section.

**Comment by stevepiercy** [comment]
A link to https://docs.plone.org/working-with-content/index.html was added for CONTENT MANAGEMENT. Closing.
