### ISSUE TITLE
Deployment step is missing in travis.yml 

### ISSUE THREAD

**Issue by jensens** [plone/training.plone.org#29]
Similar to the one in 
https://github.com/plone/training/blob/49f062c9d964f7afee3f22b6f734de58ee67ec3e/.travis.yml#L28-L32
https://github.com/plone/training/blob/master/deploy.sh

**Comment by jensens** [comment]
cc @svx

**Comment by mauritsvanrees** [comment]
We don't use Travis anymore, so I think this can be closed.

**Comment by stevepiercy** [comment]
Not only that, but we are planning on archiving this repo. See https://community.plone.org/t/kill-off-hugo-site-for-training/15556
