### ISSUE TITLE
Please push latest

### ISSUE THREAD

**Issue by fulv** [plone/training.plone.org#3]
The current content of plone/training/plone_training_config/instructions.rst needs to be live on training.plone.org ASAP, so attendees can start installing well in advance of the training.

**Comment by svx** [comment]
done

**Comment by fulv** [comment]
http://training.plone.org/5/plone_training_config/instructions.html is still the old content.  You can see that  the very first sentence is different from the one on https://github.com/plone/training/blob/master/plone_training_config/instructions.rst.

**Comment by svx** [comment]
fixed
